import { client } from '@/sanity/lib/client'
import {
  seoQuery,
  navbarQuery,
  heroQuery,
  logosQuery,
  statsQuery,
  mealsQuery,
  perksQuery,
  appFeaturesQuery,
  ctaBannerQuery,
  stepsQuery,
  calculatorQuery,
  testimonialsQuery,
  contactQuery,
  supportQuery,
  faqQuery,
  footerQuery,
} from './queries'

const opts = { next: { revalidate: 0 } }

export async function fetchHomepageData() {
  const [
    seo,
    navbar,
    hero,
    logos,
    stats,
    meals,
    perks,
    appFeatures,
    ctaBanner,
    steps,
    calculator,
    testimonials,
    contact,
    support,
    faq,
    footer,
  ] = await Promise.all([
    client.fetch(seoQuery,           {}, opts),
    client.fetch(navbarQuery,        {}, opts),
    client.fetch(heroQuery,          {}, opts),
    client.fetch(logosQuery,         {}, opts),
    client.fetch(statsQuery,         {}, opts),
    client.fetch(mealsQuery,         {}, opts),
    client.fetch(perksQuery,         {}, opts),
    client.fetch(appFeaturesQuery,   {}, opts),
    client.fetch(ctaBannerQuery,     {}, opts),
    client.fetch(stepsQuery,         {}, opts),
    client.fetch(calculatorQuery,    {}, opts),
    client.fetch(testimonialsQuery,  {}, opts),
    client.fetch(contactQuery,       {}, opts),
    client.fetch(supportQuery,       {}, opts),
    client.fetch(faqQuery,           {}, opts),
    client.fetch(footerQuery,        {}, opts),
  ])

  return {
    title:              seo?.pageTitle,
    metaDescription:    seo?.metaDescription,
    globalLogoUrl:      seo?.globalLogoUrl,
    globalLogoAlt:      seo?.globalLogoAlt,
    navbar,
    heroSection:        hero,
    logosSection:       logos,
    statsSection:       stats,
    mealsSection:       meals,
    perkSection:        perks,
    appFeaturesSection: appFeatures,
    ctaBannerSection:   ctaBanner,
    stepsSection:       steps,
    calculatorSection:  calculator,
    testimonialSection: testimonials,
    contactSection:     contact,
    supportSection:     support,
    faqSection:         faq,
    footer,
  }
}
